stages:
  - build
  - deploy

image: alpine

build:dev:
  stage: build
  before_script:
    - apk update
    - apk add nodejs nodejs-npm git
    - npm install
    - npm install cli/
  script:
    - npm run-script build
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - build/
    expire_in: 1 day

deploy:dev:
  stage: deploy
  only:
    - develop
  script:
    - apk update
    - apk add curl
    - curl -X POST -F token=$TURNIERE_TUVERO_TOKEN -F ref=develop http://server.local/api/v4/projects/1/trigger/pipeline

deploy:master:
  stage: deploy
  only:
    - master
  script:
    - apk update
    - apk add curl
    - curl -X POST -F token=$TURNIERE_TUVERO_TOKEN -F ref=master http://server.local/api/v4/projects/1/trigger/pipeline
