stages:
  - build
  - deploy

variables:
  SERVER_HOSTNAME: "server.local"
  REPOSITORY_PATH: "elor/tuvero"

image: alpine:latest

build:dev:
  stage: build
  only:
    - develop
    - /^feature-.*$/
  script:
    - apk update
    - apk add nodejs nodejs-npm git
    - npm install
    - npm install cli/
    - npm run-script build
  artifacts:
    paths:
      - build/
    expire_in: 1 month

build:release:
  stage: build
  variables:
    GIT_STRATEGY: clone
  only:
    - release
  script:
    - apk update
    - apk add nodejs nodejs-npm git openssh-client
    - mkdir -p ~/.ssh/
    - chmod 700 ~/.ssh/
    - echo "$SSH_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa ${SERVER_HOSTNAME} > ~/.ssh/known_hosts
    - git remote add server git@${SERVER_HOSTNAME}:${REPOSITORY_PATH}
    - version=$(sed -n 's/^.*"version".*:.*"\([0-9]\+\.[0-9]\+\.[0-9]\+\(-[0-9]\+\)\?\)-.*".$/\1/p' package.json)
    - npm install
    - npm install cli/
    - npm run-script release
    - find *
    - git add .
    - git commit -m "Release ${version}"
    - git checkout -b release-$version-test
    - git push --set-upstream server release-$version-test
    - echo "Done"

deploy:dev:
  stage: deploy
  only:
    - develop
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script:
    - apk update
    - apk add curl
    - curl -X POST -F token=$TURNIERE_TUVERO_TOKEN -F ref=develop http://server.local/api/v4/projects/1/trigger/pipeline
