stages:
  - build
  - deploy

before_script:
  - apk update
  - apk add nodejs nodejs-npm git
  - npm install
  - npm install cli/

build:
  stage: build
  tags:
    - alpine
  script:
    npm run-script build
