stages:
  - build
  - deploy

variables:
  SERVER_HOSTNAME: "server.local"
  REPOSITORY_PATH: "elor/tuvero"

image: alpine:latest

build:dev:
  stage: build
  only:
    - develop
    - /^feature-.*$/
  script:
    - apk update
    - apk add nodejs nodejs-npm git
    - npm install
    - npm install cli/
    - npm run-script build
  artifacts:
    paths:
      - build/
    expire_in: 1 month

build:release:
  stage: build
  only:
    - release
  script:
    - apk update
    - apk add git openssh
    - mkdir -p ~/.ssh/
    - chmod 700 ~/.ssh/
    - echo "$SSH_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - git remote show server || git remote remove server
    - git remote add server git@${SERVER_HOSTNAME}:${REPOSITORY_PATH}
    - git remote -v
    - git checkout -b this-is-a-test-again
    - git push --set-upstream server this-is-a-test
    - echo 'test' > test.txt
    - git add test.txt
    - git commit -m 'Add test.txt'
    - git push
    - echo "Done"

deploy:dev:
  stage: deploy
  only:
    - develop
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script:
    - apk update
    - apk add curl
    - curl -X POST -F token=$TURNIERE_TUVERO_TOKEN -F ref=develop http://server.local/api/v4/projects/1/trigger/pipeline
