stages:
  - build
  - deploy
  - stage
  - release

variables:
  SERVER_HOSTNAME: "server.fritz.box"
  REPOSITORY_PATH: "elor/tuvero"

build:dev:
  stage: build
  only:
    - develop
    - /^feature-.*$/
  image: node:latest
  script:
    - npm install
    - npm install cli/
    - npm run-script build
  artifacts:
    name: "artifacts_develop"
    paths:
      - build/
    expire_in: 1 week

deploy:dev:
  stage: deploy
  environment:
    name: staging
  only:
    - develop
  variables:
    GIT_STRATEGY: none
  dependencies: []
  image: alpine:latest
  script:
    - apk update
    - apk add curl
    - curl -X POST -F token=$TURNIERE_TUVERO_TOKEN -F ref=master http://${SERVER_HOSTNAME}/api/v4/projects/1/trigger/pipeline

build:release:
  stage: stage
  when: manual
  allow_failure: false
  variables:
    GIT_STRATEGY: clone
  only:
    - develop
  dependencies: []
  image: alpine:latest
  before_script:
    - apk update
    - apk add nodejs nodejs-npm git openssh-client
    - mkdir -m 700 -p ~/.ssh/
    - echo "$SSH_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa ${SERVER_HOSTNAME} > ~/.ssh/known_hosts
    - git remote add server git@${SERVER_HOSTNAME}:${REPOSITORY_PATH}
    - version=$(sed -n 's/^.*"version".*:.*"\([0-9]\+\.[0-9]\+\.[0-9]\+\(-[0-9]\+\)\?\)-.*".$/\1/p' package.json)
    - git config --global user.email "info@tuvero.de"
    - git config --global user.name "Tuvero Autobuild"
    - git fetch server staging
  script:
    - git checkout -b "release-$version"
    - test -z "$version" && { echo "Cannot read version"; exit 1; }
    - sed -i -e "s/$version-[a-z][a-z0-9]*/$version/" package.json
    - npm install
    - npm run-script release
    - test -z "$(find -name '.*' -not -path './.git' -not -path '.' | tee /dev/stderr)"
    - git add -u
    - git add .
    - git commit -m "Release $version built"
    - git checkout -b staging server/staging
    - git merge -X theirs -m "Release $version" "release-$version"
    - git tag "$version"
    - git push server staging:staging --tags

deploy:release:
  stage: release
  when: manual
  allow_failure: false
  variables:
    GIT_STRATEGY: clone
  dependencies: []
  only:
    - develop
  image: alpine:latest
  before_script:
    - apk update
    - apk add git openssh-client
    - mkdir -m 700 -p ~/.ssh/
    - echo "$SSH_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t rsa ${SERVER_HOSTNAME} > ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git remote add server git@${SERVER_HOSTNAME}:${REPOSITORY_PATH}
    - git remote add github git@github.com:${REPOSITORY_PATH}
    - git config --global user.email "info@tuvero.de"
    - git config --global user.name "Tuvero Autobuild"
    - git fetch server staging
    - git fetch server master
  script:
    - git checkout -b master server/master
    - git merge --ff-only server/staging
    - git push server master:master
    - git push github master:master
