stages:
  - build
  - deploy

image: alpine

before_script:
  - apk update

build:dev:
  stage: build
  before_script:
    - apk add nodejs nodejs-npm git
    - npm install
    - npm install cli/
  script:
    - npm run-script build
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - build/
    expire_in: 1 day

deploy:dev:
  stage: deploy
  only:
    - develop
  image: google/cloud-sdk:alpine
  dependencies:
    - build:dev
  script:
    - echo "Deploy Test"
    - find *
    - echo "Deploy Success"
