stages:
  - build
  - deploy

image: alpine:latest

build:dev:
  stage: build
  except:
    - release
    - master
    - /^release-.*$/
  script:
    - apk update
    - apk add nodejs nodejs-npm git
    - npm install
    - npm install cli/
    - npm run-script build
  artifacts:
    paths:
      - build/
    expire_in: 1 month

deploy:dev:
  stage: deploy
  only:
    - develop
  variables:
    GIT_STRATEGY: none
  dependencies: []
  script:
    - apk update
    - apk add curl
    - curl -X POST -F token=$TURNIERE_TUVERO_TOKEN -F ref=develop http://server.local/api/v4/projects/1/trigger/pipeline
